# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: People Medicine
email: hello@peoplemedicine.org
tagline: regenerative design for people systems
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

newsletter:
  label: Sign Up
  blurb: Join our newsletter and we'll send you more fun stuff like this.

colors:
  pink: '#FF77F9'
  orange: '#FFA47F'
  yellow: '#F9E800'
  cyan: '#87FFDD'
  blue: '#35C7FF'
  purple: '#A992FF'
  red: '#FD4796'
  green: '#C3FF6F'

collections_dir: collections
collections:
  skills:
    output: true
  patterns:
    output: true
  philosophies:
    output: true
  offerings:
    sort_by: order
    permalink: /:collection#:name
  resources:
    output: true
    permalink: /r/:name
  posts:
    permalink: /a/:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "content/collection"
    values:
      layout: "default"
      type: collection
  -
    scope:
      path: "content/about"
    values:
      layout: "page"
      type: about
  -
    scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"
  -
    scope:
      path: ""
      type: "philosophies"
    values:
      layout: "philosophy"
  -
    scope:
      path: ""
      type: "patterns"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "skills"
    values:
      layout: "collection"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
